# Generated by Django 3.0.3 on 2020-10-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0033_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_total',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='цена'),
        ),
    ]
