# Generated by Django 3.0.3 on 2020-10-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0035_auto_20201001_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('0', 'Получен'), ('1', 'Передан ресторану'), ('2', 'Передан курьеру'), ('3', 'Доставлен')], default='0', max_length=1, verbose_name='Статус заказа'),
        ),
    ]
