# Generated by Django 3.0.3 on 2020-10-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20201003_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('0', 'Наличные'), ('1', 'Картой онлайн')], default='0', max_length=1, verbose_name='Метод оплаты'),
        ),
    ]
