# Generated by Django 3.0.3 on 2021-01-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20201007_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('RGD', 'Получен'), ('ASR', 'Передан ресторану'), ('ASC', 'Передан курьеру'), ('DLD', 'Доставлен')], default='RGD', max_length=3, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CH', 'Наличные'), ('CD', 'Картой онлайн')], default='CH', max_length=2, verbose_name='Метод оплаты'),
        ),
    ]
